# This file is provided under a MIT license.  When using or
# redistributing this file, you may do so under either license.
#
# MIT License
#
# Copyright (c) 2026 Pavel Nadein
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Generic Makefile for Linux/Windows. Include it in your project
# and specify following variables. The simply call:
#
# $ make all
#
# Contact Information:
# Pavel Nadein <pavelnadein@gmail.com>

####################### SET FOLLOWING VARIABLES ################################
#
# BUILDDIR			destanation folder
# TARGET			artifact name
# CFLAGS			C compile flags
# CPPFLAGS			C++ compile flags
# CROSS_COMPILE		toolchain path + index
# SRC				list of source files including paths
# INC				list of inlude folders
# DEF				list of compile time definitions
# EXTRAF			additional compilation flags
# LDFLAGS			extra linker flags
#
################################################################################

.PHONY: all strip static_lib dynamic_lib show_symbols objdump run

CC					:= $(CROSS_COMPILE)gcc
CPP					:= $(CROSS_COMPILE)g++
STRIP				:= $(CROSS_COMPILE)strip
AR					:= $(CROSS_COMPILE)ar
NM					:= $(CROSS_COMPILE)nm
OBJDUMP				:= $(CROSS_COMPILE)objdump

OBJS 				:= $(SRC:%=$(BUILDDIR)/$(TARGET)_$(BUILDDIR)/%.o)
INCD				:= $(addprefix -I,$(INC))
DEFS				:= $(addprefix -D,$(DEF))
EXTRAF				?= -g

# Usefull flags (-MMD to generate dependencies)
CFLAGS_EXTRA		?=	-MMD \
						-Wall \
						-Wextra \
						-Wpedantic \
						-Werror \
						-Wno-unused-parameter
CFLAGS				+= $(CFLAGS_EXTRA)
CPPFLAGS			+= $(CFLAGS_EXTRA)

RM = rm -rf -f
MKDIRP = mkdir -p

# parallel build enabled
MAKEFLAGS 			+= -j$(NUM_CORES)

ifneq ($(filter clean,$(MAKECMDGOALS)),)
.NOTPARALLEL:
endif

.PRECIOUS: %/.
%/.:
	@$(MKDIRP) $*

.PHONY: clean
clean:
	@$(RM) $(BUILDDIR)

$(BUILDDIR)/$(TARGET)_$(BUILDDIR)/%.c.o: $(subst ../,,%.c)
	@$(MKDIRP) -p $(dir $@)
	@echo "Compiling C file $<"
	@$(CC) $(CFLAGS) $(EXTRAF) -c $< -o $@ $(INCD) $(DEFS)

$(BUILDDIR)/$(TARGET)_$(BUILDDIR)/%.cpp.o: $(subst ../,,%.cpp)
	@$(MKDIRP) -p $(dir $@)
	@echo "Compiling C++ file $<"
	@$(CPP) $(CPPFLAGS) $(EXTRAF) -c $< -o $@ $(INCD) $(DEFS)

$(BUILDDIR)/$(TARGET): $(OBJS)
	@echo "Linking $@"
	@$(CPP) -o $@ $(OBJS) $(LDFLAGS)

$(BUILDDIR)/$(TARGET)_stripped: $(BUILDDIR)/$(TARGET)
	@echo "Stripping $<"
	@$(STRIP) $< -o $@

$(BUILDDIR)/$(TARGET).o: $(OBJS)
	@echo "Linking static library $@"
	@$(AR) rcs $@ $<

$(BUILDDIR)/$(TARGET).so: $(OBJS)
	@echo "Linking dynamic library $@"
	@$(CPP) -shared -o $@ $<

all: $(BUILDDIR)/$(TARGET)

strip: $(BUILDDIR)/$(TARGET)_stripped

static_lib: $(BUILDDIR)/$(TARGET).o

dynamic_lib: $(BUILDDIR)/$(TARGET).so

show_symbols: $(BUILDDIR)/$(TARGET)
	@$(NM) $(BUILDDIR)/$(TARGET)

objdump: $(BUILDDIR)/$(TARGET)
	@$(OBJDUMP) -T $(BUILDDIR)/$(TARGET)

run: $(BUILDDIR)/$(TARGET)
	@./$(BUILDDIR)/$(TARGET)

-include $(OBJS:%.o=%.d)